name: Build JSON files
on:
  push:
    branches:
      - "main"
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ["16.x"]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm ci
      - name: Compile codes
        run: npm run build:dist
      - name: Build JSON files
        run: npm run build:public
      - name: Deploy products to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_dir: ./public
      - name: Archive
        run: zip monthly_update.zip -r ./public
      - name: Create a tag
        uses: mathieudutour/github-tag-action@v5.6
        with:
          github_token: ${{ github.token }}
      - name: Create a release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release $(date +'%Y-%m-%d')
          body: |
            Release