name: Monthly Update
on:
  schedule:
    - cron: '0 0 1 * *'
  push:
    branches: [ 'main' ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build
        run: cargo build --verbose

      - name: Generate JSON files
        run: ./target/debug/zipcode-japan

      - name: Deploy files to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_dir: ./public 